/**
 * Generated by '@kontent-ai/model-generator@5.10.0'
 *
 * Project name: Task Configuration
 * Environment: Release 1
 * Project Id: d609bef7-92b0-0090-b74b-e6bda6604f21
 */
export const collections = {
  /**
   * Task Creator
   */
  default: {
    codename: 'default',
    id: '00000000-0000-0000-0000-000000000000',
    name: 'Task Creator',
  },

  /**
   * Technical User
   */
  technical_user: {
    codename: 'technical_user',
    id: '76cfe7b3-24e4-4fb1-a782-7ac58d1ec8a8',
    name: 'Technical User',
  },
} as const;
