/**
 * Generated by '@kontent-ai/model-generator@5.10.0'
 *
 * Project name: Task Configuration
 * Environment: Release 1
 * Project Id: d609bef7-92b0-0090-b74b-e6bda6604f21
 */
export const contentTypes = {
  /**
   * BusinessRole
   */
  businessrole: {
    codename: 'businessrole',
    id: 'c5260705-79e7-4b6e-b799-61742939d37b',
    externalId: undefined,
    name: 'BusinessRole',
    elements: {
      /**
       * BusinessRoleId (text)
       *
       * Source: https://wiki.unum.com/wiki/Business_roles_matrix
       */
      businessroleid: {
        codename: 'businessroleid',
        id: '79cf3d08-8c42-4387-b235-60d0a5f57279',
        externalId: undefined,
        name: 'BusinessRoleId',
        required: false,
        type: 'text',
        snippetCodename: undefined,
      },

      /**
       * BusinessRoleType (text)
       *
       * Source: https://wiki.unum.com/wiki/Business_roles_matrix
       */
      businessroletype: {
        codename: 'businessroletype',
        id: 'd524c136-7f2c-4a4f-9bf7-00455dfcebaf',
        externalId: undefined,
        name: 'BusinessRoleType',
        required: false,
        type: 'text',
        snippetCodename: undefined,
      },
    },
  },

  /**
   * DescriptionByBusinessRole
   */
  descriptionbybusinessrole: {
    codename: 'descriptionbybusinessrole',
    id: 'bd7af076-4bf8-4c25-b73a-68d5eb7f1a1e',
    externalId: undefined,
    name: 'DescriptionByBusinessRole',
    elements: {
      /**
       * BusinessRole (modular_content)
       */
      businessrole: {
        codename: 'businessrole',
        id: '452f06de-1089-4965-b47a-c70ea4821596',
        externalId: undefined,
        name: 'BusinessRole',
        required: false,
        type: 'modular_content',
        snippetCodename: undefined,
      },

      /**
       * Message (text)
       */
      message: {
        codename: 'message',
        id: '6cdce62d-0aa4-4823-857f-a902b43bb3a0',
        externalId: undefined,
        name: 'Message',
        required: false,
        type: 'text',
        snippetCodename: undefined,
      },
    },
  },

  /**
   * DueDateSetting
   */
  duedatesetting: {
    codename: 'duedatesetting',
    id: '23c4f723-8fab-4f6e-9c1c-041971baac46',
    externalId: undefined,
    name: 'DueDateSetting',
    elements: {
      /**
       * DueDateDays (number)
       *
       * Date used in due date calculation i.e. ReferenceDate + DueDateDays = DueDate
       */
      duedatedays: {
        codename: 'duedatedays',
        id: '306931fb-14b5-4ad7-bb98-8c66cb9424d9',
        externalId: undefined,
        name: 'DueDateDays',
        required: true,
        type: 'number',
        snippetCodename: undefined,
      },

      /**
       * ReferenceDate (multiple_choice)
       *
       * Date used in due date calculation i.e. ReferenceDate + DueDateDays = DueDate
       */
      referencedate: {
        codename: 'referencedate',
        id: '6893163c-151a-408b-8473-6a66dbe5b4f1',
        externalId: undefined,
        name: 'ReferenceDate',
        required: true,
        type: 'multiple_choice',
        snippetCodename: undefined,
      },
    },
  },

  /**
   * Event
   */
  event: {
    codename: 'event',
    id: '44407fb8-8d5a-4fe1-a558-9cc9050edfb9',
    externalId: undefined,
    name: 'Event',
    elements: {
      /**
       * Event Filter(s) (custom)
       */
      event_filter_s_: {
        codename: 'event_filter_s_',
        id: '32aafdaa-be7b-473c-b1b0-972bd76864c3',
        externalId: undefined,
        name: 'Event Filter(s)',
        required: false,
        type: 'custom',
        snippetCodename: undefined,
      },

      /**
       * Event to hook (custom)
       */
      event_to_hook: {
        codename: 'event_to_hook',
        id: 'd2d8d435-0d27-4048-a2d0-d564cf73c38b',
        externalId: undefined,
        name: 'Event to hook',
        required: false,
        type: 'custom',
        snippetCodename: undefined,
      },
    },
  },

  /**
   * FAQ
   */
  faq: {
    codename: 'faq',
    id: '9af60ce5-394d-4d4f-97d8-f5f6697097e3',
    externalId: undefined,
    name: 'FAQ',
    elements: {
      /**
       * BusinessRole (modular_content)
       */
      businessrole: {
        codename: 'businessrole',
        id: '3421efe7-833d-4381-9d1b-4f4476265e20',
        externalId: undefined,
        name: 'BusinessRole',
        required: true,
        type: 'modular_content',
        snippetCodename: undefined,
      },

      /**
       * Question (text)
       */
      question: {
        codename: 'question',
        id: 'd657d96e-631a-4dc7-87df-10969a33b7c6',
        externalId: undefined,
        name: 'Question',
        required: true,
        type: 'text',
        snippetCodename: undefined,
      },

      /**
       * Response (custom)
       */
      response: {
        codename: 'response',
        id: '78c58224-4ed9-4f99-aa8a-2cea144f4986',
        externalId: undefined,
        name: 'Response',
        required: true,
        type: 'custom',
        snippetCodename: undefined,
      },
    },
  },

  /**
   * Form
   */
  form: {
    codename: 'form',
    id: '463e58d9-d3ae-42e3-a27e-770e8e49afcf',
    externalId: undefined,
    name: 'Form',
    elements: {
      /**
       * ActionEvent (modular_content)
       */
      actionevent: {
        codename: 'actionevent',
        id: '7e41b56d-0133-4d93-a9d7-2727fc765b20',
        externalId: undefined,
        name: 'ActionEvent',
        required: false,
        type: 'modular_content',
        snippetCodename: undefined,
      },

      /**
       * Description (text)
       *
       * Customer Facing Form Description
       */
      description: {
        codename: 'description',
        id: 'e10187d8-1c78-4a1a-acb5-944b6ba3cb47',
        externalId: undefined,
        name: 'Description',
        required: false,
        type: 'text',
        snippetCodename: undefined,
      },

      /**
       * FormElements (modular_content)
       *
       * Questions and Informational Text on Form
       */
      formelements: {
        codename: 'formelements',
        id: '134431ee-1f8c-41d9-8a98-023df2bc9a06',
        externalId: undefined,
        name: 'FormElements',
        required: false,
        type: 'modular_content',
        snippetCodename: undefined,
      },

      /**
       * Title (text)
       *
       * Customer Facing Form Title
       */
      title: {
        codename: 'title',
        id: '736f8e7f-e274-4ab9-9229-d3c29ee26314',
        externalId: undefined,
        name: 'Title',
        required: false,
        type: 'text',
        snippetCodename: undefined,
      },
    },
  },

  /**
   * Form Config
   */
  form_config: {
    codename: 'form_config',
    id: '6cdeffca-2396-48a1-9146-288d1b46b148',
    externalId: undefined,
    name: 'Form Config',
    elements: {
      /**
       * Form Elements (modular_content)
       */
      form_elements: {
        codename: 'form_elements',
        id: '67b06545-0f90-4805-ba5a-8ac3a567d788',
        externalId: undefined,
        name: 'Form Elements',
        required: true,
        type: 'modular_content',
        snippetCodename: undefined,
      },
    },
  },

  /**
   * Form Element
   */
  form_element: {
    codename: 'form_element',
    id: 'cc2efc45-b964-4434-8ee9-9421f5859d55',
    externalId: undefined,
    name: 'Form Element',
    elements: {
      /**
       * Form (text)
       *
       * The form this element is a question on.  Allows for sibling elements to be used in show/hide logic and validation logic
       */
      form: {
        codename: 'form',
        id: 'd7736e76-96c0-47c4-8cf9-eec672a1909c',
        externalId: undefined,
        name: 'Form',
        required: true,
        type: 'text',
        snippetCodename: undefined,
      },

      /**
       * Help Text (modular_content)
       */
      help_text: {
        codename: 'help_text',
        id: 'efa17551-bf50-4da9-b5ab-195ee0493f7d',
        externalId: undefined,
        name: 'Help Text',
        required: false,
        type: 'modular_content',
        snippetCodename: undefined,
      },

      /**
       * Input Type (modular_content)
       */
      input_type: {
        codename: 'input_type',
        id: '51889654-25b4-4b94-a5c0-8686ae065e08',
        externalId: undefined,
        name: 'Input Type',
        required: true,
        type: 'modular_content',
        snippetCodename: undefined,
      },

      /**
       * Label (custom)
       */
      label: {
        codename: 'label',
        id: 'e1be60e0-0e32-41c6-9ada-37cc9669e2f3',
        externalId: undefined,
        name: 'Label',
        required: true,
        type: 'custom',
        snippetCodename: undefined,
      },

      /**
       * Required (multiple_choice)
       */
      required: {
        codename: 'required',
        id: '8c8ceb07-2fc4-4242-bdaa-8e9922c5a276',
        externalId: undefined,
        name: 'Required',
        required: true,
        type: 'multiple_choice',
        snippetCodename: undefined,
      },

      /**
       * Show Logic (TBD) (custom)
       */
      show_logic: {
        codename: 'show_logic',
        id: '2d05351a-8f0b-402b-b3fd-9801e01532dd',
        externalId: undefined,
        name: 'Show Logic (TBD)',
        required: false,
        type: 'custom',
        snippetCodename: undefined,
      },

      /**
       * Validations (custom)
       */
      validations: {
        codename: 'validations',
        id: 'faeb9880-0e82-4075-8803-a7718942a4f8',
        externalId: undefined,
        name: 'Validations',
        required: false,
        type: 'custom',
        snippetCodename: undefined,
      },
    },
  },

  /**
   * Form Text Element
   */
  form_text_element: {
    codename: 'form_text_element',
    id: '9567803e-ba01-44a3-91c8-ea4b6c1bb541',
    externalId: undefined,
    name: 'Form Text Element',
    elements: {
      /**
       * Text (custom)
       */
      text: {
        codename: 'text',
        id: '569e1e86-af4c-4c20-a35f-14d0a2c81d9a',
        externalId: undefined,
        name: 'Text',
        required: true,
        type: 'custom',
        snippetCodename: undefined,
      },
    },
  },

  /**
   * FormElement
   */
  formelement: {
    codename: 'formelement',
    id: 'cba3b184-4924-4ed5-99ba-bfa18d6bb62d',
    externalId: undefined,
    name: 'FormElement',
    elements: {
      /**
       * InputLabel (text)
       *
       * Form Label
       */
      inputlabel: {
        codename: 'inputlabel',
        id: 'ef9a2498-3665-4196-b0e5-e5c5636baf62',
        externalId: undefined,
        name: 'InputLabel',
        required: true,
        type: 'text',
        snippetCodename: undefined,
      },

      /**
       * InputName (text)
       *
       * Form Input Name
       */
      inputname: {
        codename: 'inputname',
        id: '98a8cc70-6ae0-4d93-8f8b-dc102e432a61',
        externalId: undefined,
        name: 'InputName',
        required: true,
        type: 'text',
        snippetCodename: undefined,
      },

      /**
       * InputType (modular_content)
       */
      inputtype: {
        codename: 'inputtype',
        id: '13baf3b8-77d7-4527-97c0-4ccd64b4b432',
        externalId: undefined,
        name: 'InputType',
        required: false,
        type: 'modular_content',
        snippetCodename: undefined,
      },

      /**
       * Tooltip (modular_content)
       */
      tooltip: {
        codename: 'tooltip',
        id: '30476aa5-29aa-44f9-b164-e23bfa46d5cc',
        externalId: undefined,
        name: 'Tooltip',
        required: false,
        type: 'modular_content',
        snippetCodename: undefined,
      },
    },
  },

  /**
   * FrequentlyUsedTasksByCaseType
   */
  frequentlyusedtasksbycasetype: {
    codename: 'frequentlyusedtasksbycasetype',
    id: '540807a5-35a5-4e92-ac24-e8286f3bea22',
    externalId: undefined,
    name: 'FrequentlyUsedTasksByCaseType',
    elements: {
      /**
       * Case Type (taxonomy)
       */
      case_type: {
        codename: 'case_type',
        id: '20e95f6e-833f-4fa0-9487-d42fc34bd308',
        externalId: undefined,
        name: 'Case Type',
        required: true,
        type: 'taxonomy',
        snippetCodename: undefined,
      },

      /**
       * Frequently Used Tasks (modular_content)
       */
      frequently_used_tasks: {
        codename: 'frequently_used_tasks',
        id: '71e7c7e5-7511-49f7-b964-605ba91f8cae',
        externalId: undefined,
        name: 'Frequently Used Tasks',
        required: true,
        type: 'modular_content',
        snippetCodename: undefined,
      },
    },
  },

  /**
   * InputTypeCheckbox
   */
  inputtypecheckbox: {
    codename: 'inputtypecheckbox',
    id: 'ab9898e5-3fa7-49b0-b0d9-85cd0c5e6869',
    externalId: undefined,
    name: 'InputTypeCheckbox',
    elements: {
      /**
       * Options (modular_content)
       */
      options: {
        codename: 'options',
        id: 'cdd1392e-40cd-41a3-8a52-491b8ed429bb',
        externalId: undefined,
        name: 'Options',
        required: true,
        type: 'modular_content',
        snippetCodename: undefined,
      },
    },
  },

  /**
   * InputTypeDatePicker
   */
  inputtypedatepicker: {
    codename: 'inputtypedatepicker',
    id: 'af35ce8b-36eb-4fa5-ba23-10ea4c8ba890',
    externalId: undefined,
    name: 'InputTypeDatePicker',
    elements: {
      /**
       * DateFormat (text)
       */
      dateformat: {
        codename: 'dateformat',
        id: '0dee64e6-04fe-4ebf-8dbd-0027ce47038d',
        externalId: undefined,
        name: 'DateFormat',
        required: false,
        type: 'text',
        snippetCodename: undefined,
      },
    },
  },

  /**
   * InputTypeDateTime
   */
  inputtypedatetime: {
    codename: 'inputtypedatetime',
    id: '5f25fc27-263a-4771-96fb-1901f4fc6dd6',
    externalId: undefined,
    name: 'InputTypeDateTime',
    elements: {
      /**
       * DateTimeFormat (text)
       */
      datetimeformat: {
        codename: 'datetimeformat',
        id: '539bf557-5986-4c0a-9d1c-9c51c313f0ee',
        externalId: undefined,
        name: 'DateTimeFormat',
        required: false,
        type: 'text',
        snippetCodename: undefined,
      },
    },
  },

  /**
   * InputTypeFileUpload
   */
  inputtypefileupload: {
    codename: 'inputtypefileupload',
    id: '109e02d4-f5a6-4ac6-9e05-f05bd4345807',
    externalId: undefined,
    name: 'InputTypeFileUpload',
    elements: {
      /**
       * FineosDocType (text)
       */
      fineosdoctype: {
        codename: 'fineosdoctype',
        id: 'd22d2fee-eb76-428b-b60b-5e3d1289329f',
        externalId: undefined,
        name: 'FineosDocType',
        required: false,
        type: 'text',
        snippetCodename: undefined,
      },
    },
  },

  /**
   * InputTypeOption
   */
  inputtypeoption: {
    codename: 'inputtypeoption',
    id: '3d0baa0a-9a2a-4dc6-911f-edeea0bf4856',
    externalId: undefined,
    name: 'InputTypeOption',
    elements: {
      /**
       * Label (text)
       */
      label: {
        codename: 'label',
        id: '0492ab58-414e-490d-9bca-fe129e9e2341',
        externalId: undefined,
        name: 'Label',
        required: false,
        type: 'text',
        snippetCodename: undefined,
      },
    },
  },

  /**
   * InputTypeRadioButtonGroup
   */
  inputtyperadiobutton: {
    codename: 'inputtyperadiobutton',
    id: '633b8587-57b1-4dfb-a64f-7fadaea099e2',
    externalId: undefined,
    name: 'InputTypeRadioButtonGroup',
    elements: {
      /**
       * Options (modular_content)
       */
      options: {
        codename: 'options',
        id: '0dc0dd57-c43d-49af-80e8-53d005e34b5f',
        externalId: undefined,
        name: 'Options',
        required: true,
        type: 'modular_content',
        snippetCodename: undefined,
      },
    },
  },

  /**
   * InputTypeSelect
   */
  inputtypeselect: {
    codename: 'inputtypeselect',
    id: '404244a1-3e2f-4909-adad-531c0bb432ac',
    externalId: undefined,
    name: 'InputTypeSelect',
    elements: {
      /**
       * Options (modular_content)
       */
      options: {
        codename: 'options',
        id: '483d3363-fa40-4f60-87f1-7fbc335fbe5a',
        externalId: undefined,
        name: 'Options',
        required: true,
        type: 'modular_content',
        snippetCodename: undefined,
      },
    },
  },

  /**
   * InputTypeTextArea
   */
  inputtypetextarea: {
    codename: 'inputtypetextarea',
    id: '29d46a8f-7d5d-4153-9b02-83a2ebf973ed',
    externalId: undefined,
    name: 'InputTypeTextArea',
    elements: {
      /**
       * MaxLength (text)
       */
      maxlength: {
        codename: 'maxlength',
        id: '40a6623c-afad-4b86-8057-2bf33d77e426',
        externalId: undefined,
        name: 'MaxLength',
        required: false,
        type: 'text',
        snippetCodename: undefined,
      },
    },
  },

  /**
   * InputTypeTextField
   */
  inputtypetext: {
    codename: 'inputtypetext',
    id: '49d4a6fa-4203-450e-9c04-1c99ce91d67f',
    externalId: undefined,
    name: 'InputTypeTextField',
    elements: {
      /**
       * MaxLength (text)
       */
      maxlength: {
        codename: 'maxlength',
        id: '22e9b794-c14b-431a-a5fd-e2272c636ca6',
        externalId: undefined,
        name: 'MaxLength',
        required: false,
        type: 'text',
        snippetCodename: undefined,
      },
    },
  },

  /**
   * NotificationSetting
   */
  notificationsetting: {
    codename: 'notificationsetting',
    id: 'aed8c6dc-1294-4e70-a427-fd8935e41154',
    externalId: undefined,
    name: 'NotificationSetting',
    elements: {
      /**
       * NotificationDays (number)
       *
       * Number used in notification calculation i.e. ReferenceDate + NotificationDays = NotificationDate
       */
      notificationdays: {
        codename: 'notificationdays',
        id: '23c2aa67-c252-4aa3-9b30-cec51bb9e885',
        externalId: undefined,
        name: 'NotificationDays',
        required: true,
        type: 'number',
        snippetCodename: undefined,
      },

      /**
       * NotificationTemplateRef (text)
       *
       * References the expected template id to use (i.e. Usher)
       */
      notificationtemplateref: {
        codename: 'notificationtemplateref',
        id: '19d60ff2-1dd5-40f7-950c-4ccc6ec35fad',
        externalId: undefined,
        name: 'NotificationTemplateRef',
        required: false,
        type: 'text',
        snippetCodename: undefined,
      },

      /**
       * ReferenceDate (multiple_choice)
       *
       * Date used in notification calculation i.e. ReferenceDate + NotificationDays = NotificationDate
       */
      referencedate: {
        codename: 'referencedate',
        id: 'b990f310-eb57-4328-9d34-d61fb4204efd',
        externalId: undefined,
        name: 'ReferenceDate',
        required: true,
        type: 'multiple_choice',
        snippetCodename: undefined,
      },

      /**
       * Title (text)
       */
      title: {
        codename: 'title',
        id: '0192fc5b-f236-4ce5-8143-2c1283942d1f',
        externalId: undefined,
        name: 'Title',
        required: true,
        type: 'text',
        snippetCodename: undefined,
      },
    },
  },

  /**
   * NotificationType
   */
  notificationtype: {
    codename: 'notificationtype',
    id: '643f0e6f-f5fe-4fd5-8956-191d9ae29333',
    externalId: undefined,
    name: 'NotificationType',
    elements: {
      /**
       * BusinessRole (modular_content)
       */
      businessrole: {
        codename: 'businessrole',
        id: '7a18ddf6-3ae5-4df3-970f-b25ca3eacc03',
        externalId: undefined,
        name: 'BusinessRole',
        required: false,
        type: 'modular_content',
        snippetCodename: undefined,
      },

      /**
       * Email Body (text)
       */
      email_body: {
        codename: 'email_body',
        id: 'b1eb1f22-759c-43e7-a15f-ca4438b5ebff',
        externalId: undefined,
        name: 'Email Body',
        required: false,
        type: 'text',
        snippetCodename: undefined,
      },

      /**
       * Email Subject (text)
       */
      email_subject: {
        codename: 'email_subject',
        id: '00f0b6af-fb2f-4bc4-84c3-55cf00223899',
        externalId: undefined,
        name: 'Email Subject',
        required: false,
        type: 'text',
        snippetCodename: undefined,
      },

      /**
       * SMS Message (text)
       */
      sms_message: {
        codename: 'sms_message',
        id: '4d609e40-70ef-453c-9ccb-abb69423acdf',
        externalId: undefined,
        name: 'SMS Message',
        required: false,
        type: 'text',
        snippetCodename: undefined,
      },
    },
  },

  /**
   * Persona Based Text
   */
  persona_based_text: {
    codename: 'persona_based_text',
    id: '196470ea-198b-45b8-8dce-2e19988ae481',
    externalId: undefined,
    name: 'Persona Based Text',
    elements: {
      /**
       * Persona (taxonomy)
       */
      persona: {
        codename: 'persona',
        id: 'cfa14538-5b30-452a-938c-de7b8cdbdd2c',
        externalId: undefined,
        name: 'Persona',
        required: true,
        type: 'taxonomy',
        snippetCodename: undefined,
      },

      /**
       * Text (custom)
       */
      text: {
        codename: 'text',
        id: '619c6324-6a3a-4224-9a8a-996ef88dcc41',
        externalId: undefined,
        name: 'Text',
        required: true,
        type: 'custom',
        snippetCodename: undefined,
      },
    },
  },

  /**
   * Task
   */
  task: {
    codename: 'task',
    id: 'f4910321-bce6-40c9-be21-63bfad45d445',
    externalId: undefined,
    name: 'Task',
    elements: {
      /**
       * Category (multiple_choice)
       *
       * Required - This must be done, Recommended - Potentially benefits employee
       */
      category: {
        codename: 'category',
        id: '363fbf4a-65d5-402f-9f2a-3c6742e7ab94',
        externalId: undefined,
        name: 'Category',
        required: false,
        type: 'multiple_choice',
        snippetCodename: undefined,
      },

      /**
       * Description (modular_content)
       *
       * Task will be displayed to the users based on the business role description provided.
       */
      description: {
        codename: 'description',
        id: '4b1f59fd-539c-431d-b5b1-728810520e21',
        externalId: undefined,
        name: 'Description',
        required: false,
        type: 'modular_content',
        snippetCodename: undefined,
      },

      /**
       * DueDateSettings (modular_content)
       *
       * Used to determine the due date of the task.
       */
      duedatesettings: {
        codename: 'duedatesettings',
        id: '746b3eb8-b9c9-4d84-8a72-ef7e23c341f5',
        externalId: undefined,
        name: 'DueDateSettings',
        required: false,
        type: 'modular_content',
        snippetCodename: undefined,
      },

      /**
       * FollowUpTask (modular_content)
       *
       * Follow up task to trigger when a task is partially fulfilled, but is determined incomplete.
       */
      followuptask: {
        codename: 'followuptask',
        id: '1a8790fa-71b7-4cee-af0f-b693d32642cf',
        externalId: undefined,
        name: 'FollowUpTask',
        required: false,
        type: 'modular_content',
        snippetCodename: undefined,
      },

      /**
       * Form (modular_content)
       */
      form: {
        codename: 'form',
        id: '155ff8c6-cd28-41cd-91d5-ac45cb3f0547',
        externalId: undefined,
        name: 'Form',
        required: false,
        type: 'modular_content',
        snippetCodename: undefined,
      },

      /**
       * Frequently Asked Questions (modular_content)
       */
      frequently_asked_questions: {
        codename: 'frequently_asked_questions',
        id: '944c610f-4c9a-42a5-ac6b-4dc23e311534',
        externalId: undefined,
        name: 'Frequently Asked Questions',
        required: false,
        type: 'modular_content',
        snippetCodename: undefined,
      },

      /**
       * Important Task (multiple_choice)
       */
      important_task: {
        codename: 'important_task',
        id: '5388f945-be0e-4f4c-af1c-c3f059b3c8ec',
        externalId: undefined,
        name: 'Important Task',
        required: true,
        type: 'multiple_choice',
        snippetCodename: undefined,
      },

      /**
       * Name (text)
       *
       * Task Name
       */
      name: {
        codename: 'name',
        id: 'e4859a4d-9f65-4e96-b951-903d80d33403',
        externalId: undefined,
        name: 'Name',
        required: true,
        type: 'text',
        snippetCodename: undefined,
      },

      /**
       * Short Description (modular_content)
       */
      short_description: {
        codename: 'short_description',
        id: '3289ef5a-e2d2-49d3-b520-403f35d82699',
        externalId: undefined,
        name: 'Short Description',
        required: false,
        type: 'modular_content',
        snippetCodename: undefined,
      },

      /**
       * Tags (taxonomy)
       */
      tags: {
        codename: 'tags',
        id: '21e66742-3f54-4f56-a4ec-9418718dfd9b',
        externalId: undefined,
        name: 'Tags',
        required: false,
        type: 'taxonomy',
        snippetCodename: undefined,
      },

      /**
       * Task Title (modular_content)
       *
       * Task Display Name
       */
      task_title: {
        codename: 'task_title',
        id: '76df49ee-f12b-4f19-992b-72da0db97c5b',
        externalId: undefined,
        name: 'Task Title',
        required: false,
        type: 'modular_content',
        snippetCodename: undefined,
      },

      /**
       * Tasker (modular_content)
       */
      tasker: {
        codename: 'tasker',
        id: 'c8e80715-e4ee-4bc5-b5d9-138df79c81e6',
        externalId: undefined,
        name: 'Tasker',
        required: true,
        type: 'modular_content',
        snippetCodename: undefined,
      },
    },
  },

  /**
   * TaskStatusEventMapping
   */
  taskstatusevent: {
    codename: 'taskstatusevent',
    id: '2bbb0d26-b963-46df-ac38-a816444e75e0',
    externalId: undefined,
    name: 'TaskStatusEventMapping',
    elements: {},
  },
} as const;
