/**
 * Generated by '@kontent-ai/model-generator@5.10.0'
 *
 * Project name: Task Configuration
 * Environment: Release 1
 * Project Id: d609bef7-92b0-0090-b74b-e6bda6604f21
 */
export const languages = {
  /**
   * Default project language
   */
  default: {
    codename: 'default',
    id: '00000000-0000-0000-0000-000000000000',
    isActive: true,
    isDefault: true,
    fallbackLanguageId: '00000000-0000-0000-0000-000000000000',
    externalId: undefined,
    name: 'Default project language',
  },
} as const;
