/**
 * Generated by '@kontent-ai/model-generator@5.10.0'
 *
 * Project name: Task Configuration
 * Environment: Release 1
 * Project Id: d609bef7-92b0-0090-b74b-e6bda6604f21
 */
export const roles = {
  /**
   * Project manager
   */
  projectManager: {
    codename: 'project-manager',
    id: '5d66ca22-4f31-49d1-bfb3-f0613dbbb33f',
    name: 'Project manager',
  },
} as const;
