/**
 * Generated by '@kontent-ai/model-generator@5.10.0'
 *
 * Project name: Task Configuration
 * Environment: Release 1
 * Project Id: d609bef7-92b0-0090-b74b-e6bda6604f21
 */
export const taxonomies = {
  /**
   * Case Type
   */
  case_type: {
    codename: 'case_type',
    id: '48ba8e63-aba3-48b1-b804-d24394770ae1',
    externalId: undefined,
    name: 'Case Type',
    terms: {
      accommodation_case: {
        codename: 'accommodation_case',
        id: '1aa8394e-88db-416d-b0a5-3c4e18fcdd11',
        externalId: undefined,
        name: 'Accommodation Case',
        terms: {},
      },
      bereavement: {
        codename: 'bereavement',
        id: 'a6560183-83a3-45ac-a10d-20537e13b9c6',
        externalId: undefined,
        name: 'Bereavement',
        terms: {},
      },
      care_for_a_family_member: {
        codename: 'care_for_a_family_member',
        id: 'd9cc887a-a256-4679-ad00-3b8770fb50bf',
        externalId: undefined,
        name: 'Care for a Family Member',
        terms: {},
      },
      child_bonding: {
        codename: 'child_bonding',
        id: '569c8eb8-3d0c-46d8-8da7-2147f38eea17',
        externalId: undefined,
        name: 'Child Bonding',
        terms: {},
      },
      civic_duty: {
        codename: 'civic_duty',
        id: '21ca9d57-df4f-452e-b457-b22447689f31',
        externalId: undefined,
        name: 'Civic Duty',
        terms: {},
      },
      educational_activity___employee: {
        codename: 'educational_activity___employee',
        id: '07f56e55-e36d-4c94-948a-a3b05cdc7b3b',
        externalId: undefined,
        name: 'Educational Activity - Employee',
        terms: {},
      },
      educational_activity___family: {
        codename: 'educational_activity___family',
        id: '7533b2d6-eb97-4afe-8b28-69dacbefb496',
        externalId: undefined,
        name: 'Educational Activity - Family',
        terms: {},
      },
      group_disability_claim: {
        codename: 'group_disability_claim',
        id: '83443cf4-9c46-436a-b9f4-3e5392562a3d',
        externalId: undefined,
        name: 'Group Disability Claim',
        terms: {},
      },
      leave_as_an_accommodation: {
        codename: 'leave_as_an_accommodation',
        id: 'da5ee887-966c-42a2-a43c-c7b7e7a18a8d',
        externalId: undefined,
        name: 'Leave as an Accommodation',
        terms: {},
      },
      medical_donation___employee: {
        codename: 'medical_donation___employee',
        id: '4928ca76-5476-49e3-a4a8-d1161762c7f5',
        externalId: undefined,
        name: 'Medical Donation - Employee',
        terms: {},
      },
      medical_donation___family: {
        codename: 'medical_donation___family',
        id: 'ca0f45ca-9a52-4c63-94fa-2cf6917a14da',
        externalId: undefined,
        name: 'Medical Donation - Family',
        terms: {},
      },
      military___employee: {
        codename: 'military___employee',
        id: 'c55d635c-bb51-4f25-91dc-002f1a464cc2',
        externalId: undefined,
        name: 'Military - Employee',
        terms: {},
      },
      military_caregiver: {
        codename: 'military_caregiver',
        id: 'e12e57a6-0d03-4f10-a35d-2edba491a0f6',
        externalId: undefined,
        name: 'Military Caregiver',
        terms: {},
      },
      military_exigency_family: {
        codename: 'military_exigency_family',
        id: '91d81e88-ba89-4edd-90c6-7a9cdd1c82c0',
        externalId: undefined,
        name: 'Military Exigency Family',
        terms: {},
      },
      personal___employee: {
        codename: 'personal___employee',
        id: '4cd7e72a-9ed5-43dd-8170-e05dced91d77',
        externalId: undefined,
        name: 'Personal - Employee',
        terms: {},
      },
      pregnancy_maternity: {
        codename: 'pregnancy_maternity',
        id: 'ce13389e-664d-4011-87ef-6267a80ac5fe',
        externalId: undefined,
        name: 'Pregnancy/Maternity',
        terms: {},
      },
      preventative_care___employee: {
        codename: 'preventative_care___employee',
        id: '3ff3721a-dd46-4b5a-9db4-c5930ce5709a',
        externalId: undefined,
        name: 'Preventative Care - Employee',
        terms: {},
      },
      preventative_care___family_member: {
        codename: 'preventative_care___family_member',
        id: 'f629e27a-4287-425b-b278-1fd6fb859100',
        externalId: undefined,
        name: 'Preventative Care - Family Member',
        terms: {},
      },
      serious_health_condition___employee: {
        codename: 'serious_health_condition___employee',
        id: '4c06578d-1570-4e24-b95f-23e10fecb69f',
        externalId: undefined,
        name: 'Serious Health Condition - Employee',
        terms: {},
      },
      service_in_an_elective_office: {
        codename: 'service_in_an_elective_office',
        id: 'b3c7f214-d83b-43ee-ac89-23e472ad0456',
        externalId: undefined,
        name: 'Service in an Elective Office',
        terms: {},
      },
      sickness___non_serious_health_condition___employee: {
        codename: 'sickness___non_serious_health_condition___employee',
        id: '7eec89df-7ae4-42a8-bff4-2f611215d8bf',
        externalId: undefined,
        name: 'Sickness - Non-Serious Health Condition - Employee',
        terms: {},
      },
      special_non_recurring_event: {
        codename: 'special_non_recurring_event',
        id: 'd3a9a3df-ab53-41fe-a148-18ea77f83588',
        externalId: undefined,
        name: 'Special non-recurring event',
        terms: {},
      },
      union_business: {
        codename: 'union_business',
        id: 'bf444d75-b6b2-499c-ab0e-1310e2d8e395',
        externalId: undefined,
        name: 'Union Business',
        terms: {},
      },
      volunteer_service: {
        codename: 'volunteer_service',
        id: '58a7fc89-2a1e-4306-a19e-968c2acd9484',
        externalId: undefined,
        name: 'Volunteer Service',
        terms: {},
      },
    },
  },

  /**
   * Persona
   */
  persona: {
    codename: 'persona',
    id: '4288e989-3a3d-401f-874b-d11ca8067f76',
    externalId: undefined,
    name: 'Persona',
    terms: {
      agent: {
        codename: 'agent',
        id: 'e442a4e0-be71-4319-833d-151dbfa42294',
        externalId: undefined,
        name: 'Agent',
        terms: {},
      },
      employee: {
        codename: 'employee',
        id: '05fc11fb-1c36-4afe-a82c-a09b63505a97',
        externalId: undefined,
        name: 'Employee',
        terms: {},
      },
      employer: {
        codename: 'employer',
        id: 'ba2c66a6-f8bf-48fa-83e3-ddc6fea2d028',
        externalId: undefined,
        name: 'Employer',
        terms: {},
      },
    },
  },

  /**
   * Tags
   */
  tasktype: {
    codename: 'tasktype',
    id: '5a1eb2c1-4498-4c3a-9ed7-53a6880c9e72',
    externalId: undefined,
    name: 'Tags',
    terms: {
      eligibility: {
        codename: 'eligibility',
        id: '165eded9-9ac8-4978-ad09-0d2cc28b8498',
        externalId: undefined,
        name: 'Eligibility',
        terms: {},
      },
      important: {
        codename: 'important',
        id: '31246fe2-60f1-4d14-85c1-12f22f9b02e3',
        externalId: undefined,
        name: 'Important',
        terms: {},
      },
      payment: {
        codename: 'payment',
        id: '3f8a43e5-20a0-4ade-92dc-f5de2b0d3f1a',
        externalId: undefined,
        name: 'Payment',
        terms: {},
      },
    },
  },
} as const;
