/**
 * Generated by '@kontent-ai/model-generator@5.10.0'
 *
 * Project name: Task Configuration
 * Environment: Release 1
 * Project Id: d609bef7-92b0-0090-b74b-e6bda6604f21
 */
export const workflows = {
  /**
   * Default
   * Archived step Id: 7a535a69-ad34-47f8-806a-def1fdf4d391
   * Published step Id: c199950d-99f0-4983-b711-6c4c91624b22
   */
  default: {
    codename: 'default',
    id: '00000000-0000-0000-0000-000000000000',
    name: 'Default',
  },

  /**
   * Task Creation
   * Archived step Id: 7a535a69-ad34-47f8-806a-def1fdf4d391
   * Published step Id: c199950d-99f0-4983-b711-6c4c91624b22
   */
  task_creation: {
    codename: 'task_creation',
    id: 'cb7a5422-2431-4b94-b48d-c7d7e0bd35a2',
    name: 'Task Creation',
  },
} as const;
