/**
 * Generated by '@kontent-ai/model-generator@5.10.0'
 *
 * Case Type
 * Id: 48ba8e63-aba3-48b1-b804-d24394770ae1
 * Codename: case_type
 */
export type CaseType =
  | 'accommodation_case'
  | 'bereavement'
  | 'care_for_a_family_member'
  | 'child_bonding'
  | 'civic_duty'
  | 'educational_activity___employee'
  | 'educational_activity___family'
  | 'group_disability_claim'
  | 'leave_as_an_accommodation'
  | 'medical_donation___employee'
  | 'medical_donation___family'
  | 'military___employee'
  | 'military_caregiver'
  | 'military_exigency_family'
  | 'personal___employee'
  | 'pregnancy_maternity'
  | 'preventative_care___employee'
  | 'preventative_care___family_member'
  | 'serious_health_condition___employee'
  | 'service_in_an_elective_office'
  | 'sickness___non_serious_health_condition___employee'
  | 'special_non_recurring_event'
  | 'union_business'
  | 'volunteer_service';
