import { type IContentItem, type Elements } from '@kontent-ai/delivery-sdk';
/**
 * Generated by '@kontent-ai/model-generator@5.10.0'
 *
 * BusinessRole
 * Id: c5260705-79e7-4b6e-b799-61742939d37b
 * Codename: businessrole
 */
export type BusinessRole = IContentItem<{
  /**
   * BusinessRoleId (text)
   * Required: false
   * Id: 79cf3d08-8c42-4387-b235-60d0a5f57279
   * Codename: businessroleid
   *
   * Source: https://wiki.unum.com/wiki/Business_roles_matrix
   */
  businessroleid: Elements.TextElement;

  /**
   * BusinessRoleType (text)
   * Required: false
   * Id: d524c136-7f2c-4a4f-9bf7-00455dfcebaf
   * Codename: businessroletype
   *
   * Source: https://wiki.unum.com/wiki/Business_roles_matrix
   */
  businessroletype: Elements.TextElement;
}>;
