import { type IContentItem, type Elements } from '@kontent-ai/delivery-sdk';
/**
 * Generated by '@kontent-ai/model-generator@5.10.0'
 *
 * DueDateSetting
 * Id: 23c4f723-8fab-4f6e-9c1c-041971baac46
 * Codename: duedatesetting
 */
export type DueDateSetting = IContentItem<{
  /**
   * DueDateDays (number)
   * Required: true
   * Id: 306931fb-14b5-4ad7-bb98-8c66cb9424d9
   * Codename: duedatedays
   *
   * Date used in due date calculation i.e. ReferenceDate + DueDateDays = DueDate
   */
  duedatedays: Elements.NumberElement;

  /**
   * ReferenceDate (multiple_choice)
   * Required: true
   * Id: 6893163c-151a-408b-8473-6a66dbe5b4f1
   * Codename: referencedate
   *
   * Date used in due date calculation i.e. ReferenceDate + DueDateDays = DueDate
   */
  referencedate: Elements.MultipleChoiceElement;
}>;
