import { type IContentItem, type Elements } from '@kontent-ai/delivery-sdk';
/**
 * Generated by '@kontent-ai/model-generator@5.10.0'
 *
 * Event
 * Id: 44407fb8-8d5a-4fe1-a558-9cc9050edfb9
 * Codename: event
 */
export type Event = IContentItem<{
  /**
   * Event Filter(s) (custom)
   * Required: false
   * Id: 32aafdaa-be7b-473c-b1b0-972bd76864c3
   * Codename: event_filter_s_
   */
  event_filter_s_: Elements.CustomElement;

  /**
   * Event to hook (custom)
   * Required: false
   * Id: d2d8d435-0d27-4048-a2d0-d564cf73c38b
   * Codename: event_to_hook
   */
  event_to_hook: Elements.CustomElement;
}>;
