import { type IContentItem, type Elements } from '@kontent-ai/delivery-sdk';
import { type BusinessRole } from './businessrole';

/**
 * Generated by '@kontent-ai/model-generator@5.10.0'
 *
 * FAQ
 * Id: 9af60ce5-394d-4d4f-97d8-f5f6697097e3
 * Codename: faq
 */
export type FAQ = IContentItem<{
  /**
   * BusinessRole (modular_content)
   * Required: true
   * Id: 3421efe7-833d-4381-9d1b-4f4476265e20
   * Codename: businessrole
   */
  businessrole: Elements.LinkedItemsElement<BusinessRole>;

  /**
   * Question (text)
   * Required: true
   * Id: d657d96e-631a-4dc7-87df-10969a33b7c6
   * Codename: question
   */
  question: Elements.TextElement;

  /**
   * Response (custom)
   * Required: true
   * Id: 78c58224-4ed9-4f99-aa8a-2cea144f4986
   * Codename: response
   */
  response: Elements.CustomElement;
}>;
