import { type IContentItem, type Elements } from '@kontent-ai/delivery-sdk';
/**
 * Generated by '@kontent-ai/model-generator@5.10.0'
 *
 * Form Text Element
 * Id: 9567803e-ba01-44a3-91c8-ea4b6c1bb541
 * Codename: form_text_element
 */
export type FormTextElement = IContentItem<{
  /**
   * Text (custom)
   * Required: true
   * Id: 569e1e86-af4c-4c20-a35f-14d0a2c81d9a
   * Codename: text
   */
  text: Elements.CustomElement;
}>;
