import { type IContentItem, type Elements } from '@kontent-ai/delivery-sdk';
import { type FormTextElement } from './form_text_element';
import { type InputTypeCheckbox } from './inputtypecheckbox';
import { type InputTypeDatePicker } from './inputtypedatepicker';
import { type InputTypeDateTime } from './inputtypedatetime';
import { type InputTypeFileUpload } from './inputtypefileupload';
import { type InputTypeOption } from './inputtypeoption';
import { type InputTypeRadioButtonGroup } from './inputtyperadiobutton';
import { type InputTypeTextArea } from './inputtypetextarea';
import { type InputTypeTextField } from './inputtypetext';
import { type PersonaBasedText } from './persona_based_text';

/**
 * Generated by '@kontent-ai/model-generator@5.10.0'
 *
 * Form Element
 * Id: cc2efc45-b964-4434-8ee9-9421f5859d55
 * Codename: form_element
 */
export type FormElement = IContentItem<{
  /**
   * Form (text)
   * Required: true
   * Id: d7736e76-96c0-47c4-8cf9-eec672a1909c
   * Codename: form
   *
   * The form this element is a question on.  Allows for sibling elements to be used in show/hide logic and validation logic
   */
  form: Elements.TextElement;

  /**
   * Help Text (modular_content)
   * Required: false
   * Id: efa17551-bf50-4da9-b5ab-195ee0493f7d
   * Codename: help_text
   */
  help_text: Elements.LinkedItemsElement<PersonaBasedText>;

  /**
   * Input Type (modular_content)
   * Required: true
   * Id: 51889654-25b4-4b94-a5c0-8686ae065e08
   * Codename: input_type
   */
  input_type: Elements.LinkedItemsElement<
    | InputTypeCheckbox
    | InputTypeDatePicker
    | InputTypeDateTime
    | InputTypeFileUpload
    | InputTypeOption
    | InputTypeRadioButtonGroup
    | InputTypeTextArea
    | InputTypeTextField
    | FormTextElement
  >;

  /**
   * Label (custom)
   * Required: true
   * Id: e1be60e0-0e32-41c6-9ada-37cc9669e2f3
   * Codename: label
   */
  label: Elements.CustomElement;

  /**
   * Required (multiple_choice)
   * Required: true
   * Id: 8c8ceb07-2fc4-4242-bdaa-8e9922c5a276
   * Codename: required
   */
  required: Elements.MultipleChoiceElement;

  /**
   * Show Logic (TBD) (custom)
   * Required: false
   * Id: 2d05351a-8f0b-402b-b3fd-9801e01532dd
   * Codename: show_logic
   */
  show_logic: Elements.CustomElement;

  /**
   * Validations (custom)
   * Required: false
   * Id: faeb9880-0e82-4075-8803-a7718942a4f8
   * Codename: validations
   */
  validations: Elements.CustomElement;
}>;
