import { type IContentItem, type Elements } from '@kontent-ai/delivery-sdk';
import { type CaseType } from '../taxonomies/case_type';
import { type Task } from './task';

/**
 * Generated by '@kontent-ai/model-generator@5.10.0'
 *
 * FrequentlyUsedTasksByCaseType
 * Id: 540807a5-35a5-4e92-ac24-e8286f3bea22
 * Codename: frequentlyusedtasksbycasetype
 */
export type FrequentlyUsedTasksByCaseType = IContentItem<{
  /**
   * Case Type (taxonomy)
   * Required: true
   * Id: 20e95f6e-833f-4fa0-9487-d42fc34bd308
   * Codename: case_type
   */
  case_type: Elements.TaxonomyElement<CaseType>;

  /**
   * Frequently Used Tasks (modular_content)
   * Required: true
   * Id: 71e7c7e5-7511-49f7-b964-605ba91f8cae
   * Codename: frequently_used_tasks
   */
  frequently_used_tasks: Elements.LinkedItemsElement<Task>;
}>;
