import { type IContentItem, type Elements } from '@kontent-ai/delivery-sdk';
/**
 * Generated by '@kontent-ai/model-generator@5.10.0'
 *
 * InputTypeOption
 * Id: 3d0baa0a-9a2a-4dc6-911f-edeea0bf4856
 * Codename: inputtypeoption
 */
export type InputTypeOption = IContentItem<{
  /**
   * Label (text)
   * Required: false
   * Id: 0492ab58-414e-490d-9bca-fe129e9e2341
   * Codename: label
   */
  label: Elements.TextElement;
}>;
