import { type IContentItem, type Elements } from '@kontent-ai/delivery-sdk';
/**
 * Generated by '@kontent-ai/model-generator@5.10.0'
 *
 * InputTypeTextField
 * Id: 49d4a6fa-4203-450e-9c04-1c99ce91d67f
 * Codename: inputtypetext
 */
export type InputTypeTextField = IContentItem<{
  /**
   * MaxLength (text)
   * Required: false
   * Id: 22e9b794-c14b-431a-a5fd-e2272c636ca6
   * Codename: maxlength
   */
  maxlength: Elements.TextElement;
}>;
