import { type IContentItem, type Elements } from '@kontent-ai/delivery-sdk';
/**
 * Generated by '@kontent-ai/model-generator@5.10.0'
 *
 * InputTypeTextArea
 * Id: 29d46a8f-7d5d-4153-9b02-83a2ebf973ed
 * Codename: inputtypetextarea
 */
export type InputTypeTextArea = IContentItem<{
  /**
   * MaxLength (text)
   * Required: false
   * Id: 40a6623c-afad-4b86-8057-2bf33d77e426
   * Codename: maxlength
   */
  maxlength: Elements.TextElement;
}>;
