import { type IContentItem, type Elements } from '@kontent-ai/delivery-sdk';
/**
 * Generated by '@kontent-ai/model-generator@5.10.0'
 *
 * InputTypeDateTime
 * Id: 5f25fc27-263a-4771-96fb-1901f4fc6dd6
 * Codename: inputtypedatetime
 */
export type InputTypeDateTime = IContentItem<{
  /**
   * DateTimeFormat (text)
   * Required: false
   * Id: 539bf557-5986-4c0a-9d1c-9c51c313f0ee
   * Codename: datetimeformat
   */
  datetimeformat: Elements.TextElement;
}>;
