import { type IContentItem, type Elements } from '@kontent-ai/delivery-sdk';
/**
 * Generated by '@kontent-ai/model-generator@5.10.0'
 *
 * InputTypeDatePicker
 * Id: af35ce8b-36eb-4fa5-ba23-10ea4c8ba890
 * Codename: inputtypedatepicker
 */
export type InputTypeDatePicker = IContentItem<{
  /**
   * DateFormat (text)
   * Required: false
   * Id: 0dee64e6-04fe-4ebf-8dbd-0027ce47038d
   * Codename: dateformat
   */
  dateformat: Elements.TextElement;
}>;
