import { type IContentItem, type Elements } from '@kontent-ai/delivery-sdk';
import { type InputTypeOption } from './inputtypeoption';

/**
 * Generated by '@kontent-ai/model-generator@5.10.0'
 *
 * InputTypeCheckbox
 * Id: ab9898e5-3fa7-49b0-b0d9-85cd0c5e6869
 * Codename: inputtypecheckbox
 */
export type InputTypeCheckbox = IContentItem<{
  /**
   * Options (modular_content)
   * Required: true
   * Id: cdd1392e-40cd-41a3-8a52-491b8ed429bb
   * Codename: options
   */
  options: Elements.LinkedItemsElement<InputTypeOption>;
}>;
