import { type IContentItem, type Elements } from '@kontent-ai/delivery-sdk';
/**
 * Generated by '@kontent-ai/model-generator@5.10.0'
 *
 * InputTypeFileUpload
 * Id: 109e02d4-f5a6-4ac6-9e05-f05bd4345807
 * Codename: inputtypefileupload
 */
export type InputTypeFileUpload = IContentItem<{
  /**
   * FineosDocType (text)
   * Required: false
   * Id: d22d2fee-eb76-428b-b60b-5e3d1289329f
   * Codename: fineosdoctype
   */
  fineosdoctype: Elements.TextElement;
}>;
