import { type IContentItem, type Elements } from '@kontent-ai/delivery-sdk';
import { type InputTypeOption } from './inputtypeoption';

/**
 * Generated by '@kontent-ai/model-generator@5.10.0'
 *
 * InputTypeSelect
 * Id: 404244a1-3e2f-4909-adad-531c0bb432ac
 * Codename: inputtypeselect
 */
export type InputTypeSelect = IContentItem<{
  /**
   * Options (modular_content)
   * Required: true
   * Id: 483d3363-fa40-4f60-87f1-7fbc335fbe5a
   * Codename: options
   */
  options: Elements.LinkedItemsElement<InputTypeOption>;
}>;
