import { type IContentItem, type Elements } from '@kontent-ai/delivery-sdk';
import { type InputTypeOption } from './inputtypeoption';

/**
 * Generated by '@kontent-ai/model-generator@5.10.0'
 *
 * InputTypeRadioButtonGroup
 * Id: 633b8587-57b1-4dfb-a64f-7fadaea099e2
 * Codename: inputtyperadiobutton
 */
export type InputTypeRadioButtonGroup = IContentItem<{
  /**
   * Options (modular_content)
   * Required: true
   * Id: 0dc0dd57-c43d-49af-80e8-53d005e34b5f
   * Codename: options
   */
  options: Elements.LinkedItemsElement<InputTypeOption>;
}>;
