import { type IContentItem, type Elements } from '@kontent-ai/delivery-sdk';
/**
 * Generated by '@kontent-ai/model-generator@5.10.0'
 *
 * NotificationSetting
 * Id: aed8c6dc-1294-4e70-a427-fd8935e41154
 * Codename: notificationsetting
 */
export type NotificationSetting = IContentItem<{
  /**
   * NotificationDays (number)
   * Required: true
   * Id: 23c2aa67-c252-4aa3-9b30-cec51bb9e885
   * Codename: notificationdays
   *
   * Number used in notification calculation i.e. ReferenceDate + NotificationDays = NotificationDate
   */
  notificationdays: Elements.NumberElement;

  /**
   * NotificationTemplateRef (text)
   * Required: false
   * Id: 19d60ff2-1dd5-40f7-950c-4ccc6ec35fad
   * Codename: notificationtemplateref
   *
   * References the expected template id to use (i.e. Usher)
   */
  notificationtemplateref: Elements.TextElement;

  /**
   * ReferenceDate (multiple_choice)
   * Required: true
   * Id: b990f310-eb57-4328-9d34-d61fb4204efd
   * Codename: referencedate
   *
   * Date used in notification calculation i.e. ReferenceDate + NotificationDays = NotificationDate
   */
  referencedate: Elements.MultipleChoiceElement;

  /**
   * Title (text)
   * Required: true
   * Id: 0192fc5b-f236-4ce5-8143-2c1283942d1f
   * Codename: title
   */
  title: Elements.TextElement;
}>;
