import { type IContentItem, type Elements } from '@kontent-ai/delivery-sdk';
import { type BusinessRole } from './businessrole';
import { type DescriptionByBusinessRole } from './descriptionbybusinessrole';
import { type DueDateSetting } from './duedatesetting';
import { type FAQ } from './faq';
import { type FormConfig } from './form_config';
import { type Tags } from '../taxonomies/tasktype';

/**
 * Generated by '@kontent-ai/model-generator@5.10.0'
 *
 * Task
 * Id: f4910321-bce6-40c9-be21-63bfad45d445
 * Codename: task
 */
export type Task = IContentItem<{
  /**
   * Category (multiple_choice)
   * Required: false
   * Id: 363fbf4a-65d5-402f-9f2a-3c6742e7ab94
   * Codename: category
   *
   * Required - This must be done, Recommended - Potentially benefits employee
   */
  category: Elements.MultipleChoiceElement;

  /**
   * Description (modular_content)
   * Required: false
   * Id: 4b1f59fd-539c-431d-b5b1-728810520e21
   * Codename: description
   *
   * Task will be displayed to the users based on the business role description provided.
   */
  description: Elements.LinkedItemsElement<DescriptionByBusinessRole>;

  /**
   * DueDateSettings (modular_content)
   * Required: false
   * Id: 746b3eb8-b9c9-4d84-8a72-ef7e23c341f5
   * Codename: duedatesettings
   *
   * Used to determine the due date of the task.
   */
  duedatesettings: Elements.LinkedItemsElement<DueDateSetting>;

  /**
   * FollowUpTask (modular_content)
   * Required: false
   * Id: 1a8790fa-71b7-4cee-af0f-b693d32642cf
   * Codename: followuptask
   *
   * Follow up task to trigger when a task is partially fulfilled, but is determined incomplete.
   */
  followuptask: Elements.LinkedItemsElement<Task>;

  /**
   * Form (modular_content)
   * Required: false
   * Id: 155ff8c6-cd28-41cd-91d5-ac45cb3f0547
   * Codename: form
   */
  form: Elements.LinkedItemsElement<FormConfig>;

  /**
   * Frequently Asked Questions (modular_content)
   * Required: false
   * Id: 944c610f-4c9a-42a5-ac6b-4dc23e311534
   * Codename: frequently_asked_questions
   */
  frequently_asked_questions: Elements.LinkedItemsElement<FAQ>;

  /**
   * Important Task (multiple_choice)
   * Required: true
   * Id: 5388f945-be0e-4f4c-af1c-c3f059b3c8ec
   * Codename: important_task
   */
  important_task: Elements.MultipleChoiceElement;

  /**
   * Name (text)
   * Required: true
   * Id: e4859a4d-9f65-4e96-b951-903d80d33403
   * Codename: name
   *
   * Task Name
   */
  name: Elements.TextElement;

  /**
   * Short Description (modular_content)
   * Required: false
   * Id: 3289ef5a-e2d2-49d3-b520-403f35d82699
   * Codename: short_description
   */
  short_description: Elements.LinkedItemsElement<DescriptionByBusinessRole>;

  /**
   * Tags (taxonomy)
   * Required: false
   * Id: 21e66742-3f54-4f56-a4ec-9418718dfd9b
   * Codename: tags
   */
  tags: Elements.TaxonomyElement<Tags>;

  /**
   * Task Title (modular_content)
   * Required: false
   * Id: 76df49ee-f12b-4f19-992b-72da0db97c5b
   * Codename: task_title
   *
   * Task Display Name
   */
  task_title: Elements.LinkedItemsElement<DescriptionByBusinessRole>;

  /**
   * Tasker (modular_content)
   * Required: true
   * Id: c8e80715-e4ee-4bc5-b5d9-138df79c81e6
   * Codename: tasker
   */
  tasker: Elements.LinkedItemsElement<BusinessRole>;
}>;
