import { type IContentItem } from '@kontent-ai/delivery-sdk';
/**
 * Generated by '@kontent-ai/model-generator@5.10.0'
 *
 * TaskStatusEventMapping
 * Id: 2bbb0d26-b963-46df-ac38-a816444e75e0
 * Codename: taskstatusevent
 */
export type TaskStatusEventMapping = IContentItem<{}>;
